apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-web-app
  namespace: argocd  # Argo CD typically runs in this namespace
spec:
  project: default
  source:
    repoURL: https://github.com/HasaraDA/ArgoCD.git
    targetRevision: HEAD
    path: demo-app  # Path inside the repo where manifests are located
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-web-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
