apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/HasaraDA/ArgoCD.git
    targetRevision: HEAD
    path: demo-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: simple-node-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true