apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-app
spec:
  selector:
    matchLabels:
      app: simple-node-app
  replicas: 6
  template:
    metadata:
      labels:
        app: simple-node-app
    spec:
      containers:
      - name: simple-node-app
        image: hassalaa/simple-node-app:1.0
        ports:
        - containerPort: 3000